SYMPTOMS = {
    "তীব্র পেট ব্যথা": "sharp abdominal pain",
    "বমি": "vomiting",
    "মাথা ব্যথা": "headache",
    "কাশি": "cough",
    "বুকে তীব্র ব্যথা": "sharp chest pain",
    "বমি বমি ভাব": "nausea",
    "পিঠে ব্যথা": "back pain",
    "শ্বাসকষ্ট": "shortness of breath",
    "জ্বর": "fever",
    "মাথা ঘোরা": "dizziness",
    "নাক বন্ধ": "nasal congestion",
    "পায়ে ব্যথা": "leg pain",
    "ত্বক ফুলে যাওয়া": "skin swelling",
    "মানসিক বিভ্রান্তি বা সাইকোটিক লক্ষণ": "depressive or psychotic symptoms",
    "তলপেটে ব্যথা": "lower abdominal pain",
    "গলা ব্যথা": "sore throat",
    "জ্বালাপোড়া ধরনের পেট ব্যথা": "burning abdominal pain",
    "ত্বকে ফুসকুড়ি": "skin rash",
    "হাতে ব্যথা": "arm pain",
    "দুর্বলতা": "weakness",
    "কানে ব্যথা": "ear pain",
    "ডায়রিয়া": "diarrhea",
    "অনুভূতি হারানো": "loss of sensation",
    "ত্বকে চুলকানি": "itching of skin",
    "অনিয়ন্ত্রিত অঙ্গপ্রত্যঙ্গ নড়াচড়া": "abnormal involuntary movements",
    "শ্রোণী ব্যথা": "pelvic pain",
    "চোখে ব্যথা": "pain in eye",
    "বুকে চাপ অনুভব": "chest tightness",
    "নড়াচড়ায় সমস্যা": "problems with movement",
    "দৃষ্টিশক্তি কমে যাওয়া": "diminished vision",
    "প্রস্রাবে ব্যথা": "painful urination",
    "প্রস্রাব আটকে যাওয়া": "retention of urine",
    "শ্বাস নিতে কষ্ট": "difficulty breathing",
    "হাঁটুতে ব্যথা": "knee pain",
    "মলে রক্ত": "blood in stool",
    "ঘন ঘন প্রস্রাব": "frequent urination",
    "ভ্রম বা হ্যালুসিনেশন": "delusions or hallucinations",
    "পায়ের পাতা বা আঙুলে ব্যথা": "foot or toe pain",
    "অজ্ঞান হয়ে যাওয়া": "fainting",
    "ক্ষুধামন্দা": "decreased appetite",
    "অম্বল": "heartburn",
    "চোখে চুলকানি": "itchiness of eye",
    "যোনিপথে স্রাব": "vaginal discharge",
    "প্রস্রাবে রক্ত": "blood in urine",
    "অনিয়ন্ত্রিত প্রস্রাব": "involuntary urination",
    "কাঁপুনি": "chills",
    "অনিয়মিত হৃদস্পন্দন": "irregular heartbeat",
    "কথা বলতে অসুবিধা": "difficulty speaking",
    "হৃদকম্পন": "palpitations",
    "চোখ লাল হওয়া": "eye redness",
    "পা ফুলে যাওয়া": "leg swelling",
    "অ্যালার্জিক প্রতিক্রিয়া": "allergic reaction",
    "ঠোঁট ফুলে যাওয়া": "lip swelling",
    "গিলতে অসুবিধা": "difficulty in swallowing",
    "চোখে কিছু আছে মনে হওয়া": "foreign body sensation in eye",
    "শ্রবণশক্তি কমে যাওয়া": "diminished hearing",
    "খিঁচুনি ও পেশির টান": "cramps and spasms",
    "যোনিপথে চুলকানি": "vaginal itching",
    "দৃষ্টিতে দাগ বা মেঘ দেখা": "spots or clouds in vision",
    "শ্বাসে সাঁ সাঁ শব্দ": "wheezing",
    "হাত বা আঙুল ফুলে যাওয়া": "hand or finger swelling",
    "চোখ ফুলে যাওয়া": "swollen eye",
    "দ্বৈত দৃষ্টি": "double vision",
    "মলদ্বার দিয়ে রক্তপাত": "rectal bleeding",
    "গর্ভাবস্থাজনিত সমস্যা": "problems during pregnancy",
    "খিঁচুনি": "seizures",
    "কোষ্ঠকাঠিন্য": "constipation",
    "অতিরিক্ত ঘাম": "sweating",
    "অতিরিক্ত মাসিক রক্তপাত": "heavy menstrual flow",
    "কণ্ঠস্বর ভাঙা": "hoarse voice",
    "রক্তবমি": "vomiting blood",
    "মলদ্বারে ব্যথা": "pain of the anus",
    "চোখ থেকে সাদা স্রাব": "white discharge from eye",
    "চোখে জ্বালা বা খোঁচা": "eye burns or stings",
    "মুখে ঘা": "mouth ulcer",
    "যোনিতে ব্যথা": "vaginal pain",
    "ঘুম ঘুম ভাব": "sleepiness",
    "কানে শব্দ শোনা": "ringing in ear",
    "গর্ভাবস্থায় রক্তপাত": "spotting or bleeding during pregnancy",
    "কফ ওঠা": "coughing up sputum",
    "দাঁতে ব্যথা": "toothache",
    "মুখে ব্যথা": "mouth pain",
    "শ্বাস নিলে ব্যথা": "hurts to breath",
    "অণ্ডকোষে ব্যথা": "pain in testicles",
    "গলা শক্ত লাগা": "throat feels tight",
    "সাইনাসে ব্যথা": "painful sinuses",
    "সাইনাস বন্ধ": "sinus congestion",
    "পেট ফাঁপা": "stomach bloating",
    "গলা ফুলে যাওয়া": "neck swelling",
    "রক্তসহ কাশি": "hemoptysis",
    "ব্যথাযুক্ত মাসিক": "painful menstruation",
    "অন্ধত্ব": "blindness",
    "অণ্ডথলি ফুলে যাওয়া": "swelling of scrotum",
    "মাথার ত্বকে চুলকানি": "itchy scalp",
    "গলার ভেতর ফুলে যাওয়া": "throat swelling",
    "জড়িয়ে কথা বলা": "slurring words",
    "চোখের পাতা ফুলে যাওয়া": "eyelid swelling",
    "জন্ডিস": "jaundice",
    "নাক দিয়ে রক্ত পড়া": "nosebleed"
}
def extract_bangla_symptoms(text, feature_cols):
    extracted = {}

    if not text:
        return extracted

    for bangla_word, feature_name in SYMPTOMS.items():
        if bangla_word in text and feature_name in feature_cols:
            extracted[feature_name] = 1

    return extracted